ALL_COUNTRIES = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Azerbaijan',
    'Argentina',
    'Australia',
    'Austria',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Armenia',
    'Barbados',
    'Belgium',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Belize',
    'Solomon Islands',
    'Brunei',
    'Bulgaria',
    'Myanmar',
    'Burundi',
    'Belarus',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Central African Republic',
    'Sri Lanka',
    'Chad',
    'Chile',
    'China',
    'Taiwan',
    'Colombia',
    'Comoros',
    'Congo',
    'Congo, Democratic Republic',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Benin',
    'Denmark',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'El Salvador',
    'Equatorial Guinea',
    'Ethiopia',
    'Eritrea',
    'Estonia',
    'Fiji',
    'Finland',
    'France',
    'Djibouti',
    'Gabon',
    'Georgia',
    'Gambia',
    'Germany',
    'Ghana',
    'Kiribati',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Cote d Ivoire',
    'Jamaica',
    'Japan',
    'Kazakhstan',
    'Jordan',
    'Kenya',
    'Korea, North',
    'Korea, South',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Lebanon',
    'Lesotho',
    'Latvia',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Monaco',
    'Mongolia',
    'Moldova',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Oman',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'Vanuatu',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Norway',
    'Micronesia',
    'Marshall Islands',
    'Palau',
    'Pakistan',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Guinea-Bissau',
    'Timor-Leste',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'St Kitts and Nevis',
    'St Lucia',
    'St Vincent and the Grenadines',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Vietnam',
    'Slovenia',
    'Somalia',
    'South Africa',
    'Zimbabwe',
    'Spain',
    'South Sudan',
    'Sudan',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tajikistan',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'United Arab Emirates',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'Macedonia',
    'Egypt',
    'United Kingdom',
    'Tanzania',
    'United States',
    'Burkina Faso',
    'Uruguay',
    'Uzbekistan',
    'Venezuela',
    'Samoa',
    'Yemen',
    'Zambia'
]